### ISSUE TITLE
Xbox Edge browser

### ISSUE THREAD

**Issue by Nun-z** [kootstra-rene/enge-js#9] opened 2021-03-09 10:48 UTC
I would love to get this working on Xbox, but unfortunately the console's Edge browser doesn't seem to want to load the BIOS.  Do you know if there's a workaround that might help?

**Comment by zaykho** [comment] 2021-03-09 20:28
It's not an issue with the browser, but more an issue with the latest version of enge-js.

![cxccx](https://user-images.githubusercontent.com/6943022/110533544-61846280-811e-11eb-919a-c596cfe4b6b1.png)

**Comment by kootstra-rene** [comment] 2021-03-09 20:41
I do not have access to an edge browser it seems i need to score a Windows laptop somewhere.
Give me some time to investigate

**Comment by zaykho** [comment] 2021-03-09 20:51
The problem is, does the Xbox Edge browser is the same than the one delivered on Windows ? Because I do have Windows (7) and do have also Edge installed, and it works great. 

![image](https://user-images.githubusercontent.com/6943022/110536232-80382880-8121-11eb-86c7-4c22436d02ec.png)

**Comment by kootstra-rene** [comment] 2021-03-09 20:55
I have now a machine with an older version of edge and I get also an error so I will fix it tonight. There is a piece of code which uses new JavaScript construct which I would normally always replace with the older constructs to not have these issues.

**Comment by kootstra-rene** [comment] 2021-03-09 21:19
@Nun-z can you verify it is fixed on the XBox? Then I will close this issue accordingly

**Comment by kootstra-rene** [comment] 2021-03-09 22:17
Thanks for confirming, could you make a video on how it works on an XBox? It would be kind of funny to see.

**Closed by kootstra-rene** 2021-03-09 22:17 UTC
