### ISSUE TITLE
Issue with Firefox after the update (added file upload)

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#10] opened 2021-03-09 20:47 UTC
Impossible to load a bios or a game anymore in Firefox (it does work on Chrome though), getting that error from the console log:

![dddss](https://user-images.githubusercontent.com/6943022/110535637-d22c7e80-8120-11eb-954d-5d38ee51faba.png)

` const fileList = evt.dataTransfer?.files || evt.target.files;`

I will investigate.

EDIT: this was tested with the [latest version](https://kootstra-rene.github.io/enge-js/)

**Comment by kootstra-rene** [comment] 2021-03-09 21:17
already fixed please check

**Comment by kootstra-rene** [comment] 2021-03-09 21:18
Duplicate of #9

**Closed by kootstra-rene** 2021-03-09 21:18 UTC
